/*
 * Copyright (C) 2021
 * Joseph Stephen VK7JS
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer
 *    in the documentation and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * 4. Use of this source code or binary releases for commercial purposes is strictly forbidden. This includes, without limitation,
 *    incorporation in a commercial product or incorporation into a product or project which allows commercial use.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
 * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
#ifndef _OPENGD77_AUTOZONE_H_
#define _OPENGD77_AUTOZONE_H_

#include "codeplug.h"


/*
An AutoZone is a virtual zone whose channels are autogenerated on the fly and do not take up any memory.
E.g. The Australian UHF CB band has 80 channels.
*/

typedef enum
{
	AutoZoneEnabled=0x01,
	AutoZoneModeDigital=0x02, // 0 FM, 1 DMR.
	AutoZoneInterleaveChannels=0x04, // 0 off, 1 on,
	AutoZoneDuplexEnabled=0x08,
	AutoZoneOffsetDirectionPlus=0x10, // unset is minus, set is plus. For simplex, unset prior bit.
	AutoZoneNarrow=0x20, // if not set, assumed wide.
	AutoZonePowerMask=0xf000, // 0 all rx, or max wattage allowed in increments of 0.5 w (up to 5 w).
} AutoZoneFlags_t;

typedef enum
{
	AutoZone_AU_UHFCB=1,
	AutoZone_AU_VHF_MARINE,
	AutoZone_NOAA,
	AutoZone_MURS,
	AutoZone_FRS,
	AutoZone_GMRS,
	AutoZone_TYPE_MAX
} AutoZoneType_t;

typedef struct
{
	char name[16];
	uint16_t flags; // See AutoZoneFlags_t enum.
	AutoZoneType_t type;
	uint32_t startFrequency; // mHz of first channel
	uint32_t endFrequency; // mHz of last channel
	uint16_t channelSpacing; // kHz channel step x 100.
	uint16_t repeaterOffset; // kHz.
	uint16_t priorityChannelIndex;
	uint16_t curChannelIndex;
	uint16_t totalChannels;
	uint16_t rxTone;
	uint16_t txTone;
} struct_AutoZoneParams_t;

uint16_t AutoZoneGetTotalChannels();
bool AutoZoneIsValid();
bool AutoZoneIsCurrentZone(int zoneIndex);
void AutoZoneInitialize(AutoZoneType_t type);
bool AutoZoneGetZoneDataForIndex(int zoneNum, struct_codeplugZone_t *returnBuf);
// indices are 0-based.
bool AutoZoneGetFrequenciesForIndex(uint16_t index, uint32_t* rxFreq, uint32_t* txFreq);
bool AutoZoneGetChannelData(uint16_t index, struct_codeplugChannel_t *channelBuf);
#endif //_OPENGD77_AUTOZONE_H_